### ISSUE TITLE
Adversarial Training

### ISSUE THREAD

**Issue by Yeez-lee** [RulinShao/on-the-adversarial-robustness-of-visual-transformer#2]
Hi @RulinShao, it's a quite solid work. But I have some questions about adversarial training.
(1) In your paper, you used **_ViT-B/4_** but here I only see  **_vit_base_patch2_**. So, your adv-training model is still **_ViT-B/4_**, right?
(2) In your code, I feel little bit confused about  **_`eval`_**. What's the purpose for it? You mean **_`model.eval()`_**? If so, then **_`model.train()`_** is applied. Can you give an explanation for it?
https://github.com/RulinShao/on-the-adversarial-robustness-of-visual-transformer/blob/ff8e3b7ffadd5f6776205d1b1e2b705a75bebb57/training/train.py#L45-L46
(3) In the paper, you downsampled the weights for patch embeddings and what're the codes for such operation? I only see the modification of **_patch_size_** . https://github.com/RulinShao/on-the-adversarial-robustness-of-visual-transformer/blob/ff8e3b7ffadd5f6776205d1b1e2b705a75bebb57/training/timm_vit/vit.py#L283-L286
(4) CIFAR-10 data resolution is 32 and the model in your command line is **_`vit_base_patch16_224_in21k`_** . Such large patch size for CIFAR-10 could highly do harm to acc%. Did you use such model to do the experiments? I only see the results of **_ViT-B/4_** in the paper. BTW, you always keep datasize in 32 instead of upsampling 224, right? Did you try to upsample CIFAR-10 to 224 and use patch size 16 for adversarial training?

Thanks for your help!

**Comment by shizhouxing** [comment]
Hi @Yeez-lee , thanks for your interest! Sorry for the confusion in the model name.

1. The model for adversarial training is ViT-B/4. In the implementation, it's based on `vit_base_patch16_224_in21k` but we pass custom arguments so that actually ViT-B/4 is created. `vit_base_patch2` is not related to adversarial training.
2. `eval` here is not `model.eval()`. It's a python function which means converting `args.model` (str) to the corresponding python class for the model. 
3. You may find the downsampling code [here](https://github.com/RulinShao/on-the-adversarial-robustness-of-visual-transformer/blob/ff8e3b7ffadd5f6776205d1b1e2b705a75bebb57/training/timm_vit/vit.py#L229). 

4. 
>CIFAR-10 data resolution is 32 and the model in your command line is vit_base_patch16_224_in21k . Such large patch size for CIFAR-10 could highly do harm to acc%. Did you use such model to do the experiments? I only see the results of ViT-B/4 in the paper. 

Actually the patch size is overriden to 4 by the [`--patch` argument](https://github.com/RulinShao/on-the-adversarial-robustness-of-visual-transformer/blob/master/training/parser.py#L35) so that ViT-B/4 is created.

>BTW, you always keep datasize in 32 instead of upsampling 224, right? Did you try to upsample CIFAR-10 to 224 and use patch size 16 for adversarial training?

We don't do upsampling because we want to keep the image size (32\*32) the same as appeared in previous works, so that the perturbation size is comparable for the same dataset. If we upsample the image to 224\*224, we may not be able to compare with other works using linf eps=8/255 on CIFAR-10.

**Comment by Yeez-lee** [comment]
Hi @shizhouxing , Thanks for your quick response! I have emailed you and please check your email.
